# Database Configuration
spring.application.name=ManagementInventaris
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=090208
spring.datasource.url=jdbc:postgresql://localhost:5432/inventaris
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=100
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

# Backup & Restore Configuration
backup.directory=./backup
restore.directory=./restore
backup.minio.directory=./minio-backup

# Log level for hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# Configuration Migration Flyway DB
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://localhost:5432/inventaris
spring.flyway.user=postgres
spring.flyway.password=090208
spring.flyway.locations=classpath:/db/migration

# Configuration Monitoring Spring Boot
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Configuration MINIO Uploaded Files
# Multipart Properties
spring.servlet.multipart.enabled=true
# Max File Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# MinIO Host
minio.url=http://192.168.1.28:9001
#minio.url=http://play.min.io:9443
minio.username=minioadmin
minio.password=minioadmin
minio.accessKey=pPdGvjjhBSjsLJwHcSJG
minio.secretKey=9WgNYOsZSgaiH2mmGU6r1YZfqMXGKn1MEjivPuz2
minio.bucketName=inventaris
minio.defaultProfilePath=profile/default/default_profile.jpg
put-object-part-size=5242880
spring.main.allow-bean-definition-overriding=true

# Configuration Server Host
server.host=192.168.1.26
server.port=5050

# Configuration JWT Token
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=31536000000
application.security.jwt.refresh-token.expiration=31536000000

# Configuration SMTP Server for Java Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dearlyfebrianoi@gmail.com
spring.mail.password=gquafcsxvwsguugd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true

# Timeouts
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Auto Reload Project Configuration
spring.devtools.restart.enabled=true