CREATE TABLE IF NOT EXISTS _user (
    id VARCHAR(36) NOT NULL UNIQUE SERIAL PRIMARY KEY,
    firstname VARCHAR(300) NOT NULL,
    lastname VARCHAR(300) NOT NULL,
    bioProfile VARCHAR(300) NOT NULL DEFAULT 'No Bio Yet!',
    username_user VARCHAR(255) NOT NULL,
    phone BIGINT DEFAULT 0 NOT NULL,
    email VARCHAR(300) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    gender_id INT,
    province_id CHAR(2),
    regency_id CHAR(4),
    district_id CHAR(7),
    village_id CHAR(10),
    image_url VARCHAR(255),
    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    followers_count INT NOT NULL DEFAULT 0,
    following_count INT NOT NULL DEFAULT 0,
    likes_count INT NOT NULL DEFAULT 0,
    liked_users_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    timezone_label VARCHAR(255) NOT NULL,
    FOREIGN KEY (gender_id) REFERENCES gender(id),
    FOREIGN KEY (province_id) REFERENCES provinces(id),
    FOREIGN KEY (regency_id) REFERENCES regencies(id),
    FOREIGN KEY (district_id) REFERENCES districts(id),
    FOREIGN KEY (village_id) REFERENCES villages(id)
);